### ISSUE TITLE
NR errors for IEEE 13 bus network model

### ISSUE THREAD

**Issue by dchassin** [arras-energy/gridlabd-old#1277]
## Problem description

Modifying the IEEE 13 bus network model slightly causes 2 strange NR errors.

## Steps to reproduce

1. Add a padmount single phase transformer to Load634 with a triplex node, triplex meter, and house.  This causes the following error:

~~~
ERROR    [1999-12-31 16:00:00 PST] : sync_node(obj=35;Node650): NR: duplicate admittance entry found - attaches to node Node630 - check for parallel circuits between common nodes!
~~~

2. Remove the house. This causes a segfault: 

~~~
WARNING  [INIT] : xfrmcfg_ABCN_480: This connection type on transformer:51 (xfrmcfg_ABCN_480) does not support shunt_impedance at this time.
/usr/local/bin/gridlabd: line 412: 93412 Segmentation fault: 11  "${bindir}/gridlabd.bin" "$@"
~~~

## Expected behavior

This should solve without issues.

## System information

* GridLAB-D version: `HiPAS GridLAB-D 4.3.1-230415 (develop_add_create_loads_tool) Darwin`
* Operating system: `Darwin MacBook-Pro.local 19.6.0 Darwin Kernel Version 19.6.0: Tue Jun 21 21:18:39 PDT 2022; root:xnu-6153.141.66~1/RELEASE_X86_64 x86_64`

## Additional information

This problem is blocking PR #1202. 

## Attachments

[test_create_loads.glm.zip](https://github.com/slacgismo/gridlabd/files/11242581/test_create_loads.glm.zip)

**Comment by ftuffner** [comment]
Issue appears to be with how the transformer checks phases.  I haven't looked into why it is causing the "duplicate admittance entry" issue, but the underlying cause is the "single phase" transformer (not single-phase center-tapped) going to a triplex_node.  Once you change the transformer to SPCT (or the triplex_node/triplex_meters to nodes/meters), it solves like usual.  My guess is due to how transformers store the admittance for triplex/SPCT transformers versus "three-phase", something isn't populated (because it is implied) and that makes it think it connects to the SWING node (node 0).

This same issue exists in the DOE/PNNL GridLAB-D, so I'll cross link this there.  I'll try to take a look at it in the next couple days - it may be as simple as more rigorous phase checks on the transformers
