### ISSUE TITLE
glm2json converter fails to output the object original property settings (filesave_options=ALLINITIAL)

### ISSUE THREAD

**Issue by yeyanzhu** [arras-energy/gridlabd-old#673]
## Problem description
When gridlabd glm2json converter is used to output JSON file, the object original property settings are not correctly recorded.

## Steps to reproduce
1. Set the filesave global parameters:
`#set glm_save_options=ORIGINAL`
`#set filesave_options=ALLINITIAL`
2. Use the following command to output JSON file
`gridlabd BU0001_glmfile_ts.glm -o res.json`
3. In the json output file, only the the first load object `N_800003816` keeps the original load shape settings, e.g. 
		`"constant_power_A_real": "load_shape_A*8048.07+0",`
		`"constant_power_B_real": "load_shape_B*8048.07+0",`
		`"constant_power_C_real": "load_shape_C*8048.07+0",`
		`"constant_power_A_reac": "load_shape_A*2645.27+0",`
		`"constant_power_B_reac": "load_shape_B*2645.27+0",`
		`"constant_power_C_reac": "load_shape_C*2645.27+0",`
For the other load objects, original load shape settings are replaced with numeric values.

## Expected behavior
For all the load objects, the original load shape settings should be output to json file.

## System information
* GridLAB-D version: 
`HiPAS GridLAB-D 4.2.1-200527 (develop) Linux`

## Attachments
The model files and the json output file are attached
[BU0001_JSON.zip](https://github.com/slacgismo/gridlabd/files/4715964/BU0001_JSON.zip)

**Comment by dchassin** [comment]
The specification of some loads in `BU0001_glmfile_loads.glm` are invalid. For example:

~~~
object load 
{
	name N_800003816;
	phases ABC;
	nominal_voltage 2523.021;
	constant_power_A_real load_shape_A*8048.06666667;
	constant_power_B_real load_shape_B*8048.06666667;
	constant_power_C_real load_shape_C*8048.06666667;
	constant_power_A_reac load_shape_A*2645.27159075;
	constant_power_B_reac load_shape_B*2645.27159075;
	constant_power_C_reac load_shape_C*2645.27159075;
}
~~~

is valid because the load shape is being written to a variables of type `double`, which is valid.  

However, the next load is defined as

~~~
object load {
	name N_800003814;
	phases ABC;
	nominal_voltage 2523.021;
	constant_power_A load_shape_A*4037.919;
	constant_power_B load_shape_B*4037.919;
	constant_power_C load_shape_C*4037.919;
	constant_power_A load_shape_A*1327.1997933;
	constant_power_B load_shape_B*1327.1997933;
	constant_power_C load_shape_C*1327.1997933;
}
~~~

which is invalid because `constant_power_A` is a complex quantity, while the load shape can only generate a double value. The GLM loader tolerates this because the underlying double of a complex value is its real part.  However, the JSON write does not detect this as a valid inverse mapping to obtain the initial value and ignores it.  

To avoid this problem, change the object definition to

~~~
object load {
	name N_800003814;
	phases ABC;
	nominal_voltage 2523.021;
	constant_power_A_real load_shape_A*4037.919;
	constant_power_B_real load_shape_B*4037.919;
	constant_power_C_real load_shape_C*4037.919;
	constant_power_A_reac load_shape_A*1327.1997933;
	constant_power_B_reac load_shape_B*1327.1997933;
	constant_power_C_reac load_shape_C*1327.1997933;
}
~~~
