### ISSUE TITLE
Using modulo in automated glm generation not working (SEQ_CUSTID%=6)

### ISSUE THREAD

**Issue by mlamlamla** [arras-energy/gridlabd-old#806]
## Problem description

When automatically generating glm files using `SEQ_CUSTID`, modulo does not seem to work, e.g. `SEQ_CUSTID%=6`. This could be helpful, if one has only a limited number of players to assign (e.g. 6) but wants to include >6 houses, requiring that the included player count restarts.

## Steps to reproduce

1. Include > 6 houses into glm network model:

~~~
#include using(LOADID=1,PHASE=A,COUNT=20) "house.glm"
#include using(LOADID=1,PHASE=B,COUNT=20) "house.glm"
#include using(LOADID=1,PHASE=C,COUNT=20) "house.glm"
~~~

2. Include 6 players into glm network model (player_0 ... player_5)

3. Create `house.glm` with zip-load:

		object ZIPload {
			name `zip_GLD_{SEQ_CUSTID}`;
                        base_power player_${SEQ_CUSTID%6}.value;
               }

## Expected behavior

House 6 would get assigned player_0, house 7 player_1 (because player_6 and player_7 do not exist).

## System information

HiPAS GridLAB-D 4.2.13-201027 (master) Linux
Linux 8ab714ceaef1 4.19.76-linuxkit #1 SMP Tue May 26 11:42:35 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by dchassin** [comment]
Note that step 3 will not work as expected because `${SEQ_CUSTID%6}` is evaluated only once when the implicit loop of `object house:..20` is first expanded.  To get the expression to be evaluated separately for each house in the implicit loop the ZIPload should be defined as a value expansion expression instead of a global variable expression.

    object ZIPload {
        name `zip_GLD_{SEQ_CUSTID}`;
        base_power `player_{SEQ_CUSTID%6}.value`;
    }

Inspection of the code suggest it will not work because this syntax is not supported. I believe the only allowed syntax for the expression is `SEQ_CUSTID%=6`, which write the value back into the global. I believe we should add the desired syntax for all the usual binary integer operators.

By the way, the validation test for these expression is insufficient and needs to be enhanced to check all supported syntax.
