### ISSUE TITLE
The csv_header_type options (NULL, NAME) does not work for group_recorder object

### ISSUE THREAD

**Issue by yeyanzhu** [arras-energy/gridlabd-old#842]
## Problem description
The csv_header_type options (NULL, NAME) in Tape module does not work for group_recorder object

## Steps to reproduce
1.  Run the test_pole_NR.glm (attached)
The csv_header_type is set as NAME.
2. The group_recorder output file (pole_group.csv) records the data following FULL data format. 

## Expected behavior
The csv_header_type option works for group_recorder object.

[TapeTesting.zip](https://github.com/slacgismo/gridlabd/files/5954485/TapeTesting.zip)

## System information
* GridLAB-D version: 
HiPAS GridLAB-D 4.2.15-210114 (master) Linux

**Comment by dchassin** [comment]
@yeyanzhu, would you have any objection to changing `recorder` so it uses the `group` property to act like `group_recorder` instead of trying to make `group_recorder` act like `recorder`?  The advantage is that this reduces the number of classes we have to maintain and makes the behavior of recorder more general.
