### ISSUE TITLE
Python code to process JSON dumps

### ISSUE THREAD

**Issue by jcald1** [arras-energy/gridlabd-old#92]
Requested features:

1. Implement as a python class.
2. Read and write JSON dumps and GLM MINIMAL saves
3. Sanity checks on the model:
 - header value checks (e.g., lat/lon, naming conventions)
 - basic value checks for object properties based on underlying class
 - topological processing (e.g., powerflow model structure)
4. Graphical representation
 - graph representations of model structure and powerflow structure
5. Polyglot model save/load
6. Direct translators for other tools
 - Matpower
 - CIM
 - Synergi
 - Cyme
 - OpenDSS
7. Model editing API (add, remove, set/get properties, etc.)

**Comment by dchassin** [comment]
Discussion items:
1. Add default values to JSON. @jcald1: this is already part of the glm_compile work in progress. Recommend not handling it in the python module.
1. Keep the same options in the same options in the target and source (save everything/legacy, minimal, no globals, no macros, no defaults, no internals). @jcald: that is a stretch for now. Minimal is a good first step.
1. Handle default values when converting to GLM (If a value in the JSON is the same as the default, the GLM file should not store it) - What happens if the default value changes in a new GridLAB-D version and we import an older JSON file?  The check would be made against the old default value which was stored in the JSON along with the actual value? @jcald1: ditto above, already part of the glm_compile work in progress. Recommend not handling it in the python module.
1. Should we support options for saving JSON? @jcald: yes, see above revisions to feature request.

**Comment by dpinney** [comment]
My understanding of the data flows this will enable:

![slide1](https://user-images.githubusercontent.com/2131438/50197815-cfae9600-0316-11e9-91b7-dc452313a0b7.png)

Key new capabilities are the safe interaction with the GridLAB-D data model via scripts and GUIs. It solves 2 issues with interacting with .glm files: (1) writing custom serializers/de-serializers and (2) requires handling syntax in the .glm for arbitrary computation plus a macro system.

**Comment by dchassin** [comment]
@aivanova5, please add the graph functions to the library.
